#!/usr/bin/env bash
# Generate the Arch Linux PKGBUILD for a published release.
#
# Generated rather than checked in, for the same reason as the Homebrew formula:
# a PKGBUILD carries the sha256 of an archive that does not exist until the
# release is published, so a checked-in one is either stale or wrong.
#
# Usage: generate.sh <version> [sha256]
# With no sha256 the published checksum file is fetched.
set -euo pipefail

REPO="sansyourways/Sans_Password_Manager"
version="${1:-}"
[ -n "$version" ] || { printf 'usage: generate.sh <version> [sha256]\n' >&2; exit 2; }
printf '%s' "$version" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+$' || {
	printf 'generate.sh: %s is not a version\n' "$version" >&2; exit 2; }

archive="Sans_Password_Manager_v${version}.zip"
url="https://github.com/$REPO/releases/download/v${version}/${archive}"

sha="${2:-}"
if [ -z "$sha" ]; then
	sha="$(curl -fsSL "$url.sha256" | awk 'NR==1{print $1}')"
fi
printf '%s' "$sha" | grep -Eq '^[a-f0-9]{64}$' || {
	printf 'generate.sh: %s is not a sha256\n' "$sha" >&2; exit 1; }

cat <<PKGBUILD
# Generated by packaging/aur/generate.sh for $version.
# Do not edit by hand: the sha256 below belongs to one published archive.
# Maintainer: sansyourways <sans@silentprotocol.top>
pkgname=spm
pkgver=$version
pkgrel=1
pkgdesc="Single-file encrypted password manager with a CLI and a local dashboard"
arch=('any')
url="https://github.com/$REPO"
license=('MIT')
depends=('gnupg')
optdepends=('python: local dashboard and record engine'
            'openssl: AEAD vault backend')
source=("\$pkgname-\$pkgver.zip::$url")
sha256sums=('$sha')

package() {
	cd "\$srcdir"
	# The release ships spm.sh together with the src/ it was built from, so an
	# installation can prove its own provenance rather than being asked to
	# trust it.
	install -Dm755 spm.sh "\$pkgdir/usr/bin/spm"
	install -dm755 "\$pkgdir/usr/share/spm"
	cp -r src build.sh "\$pkgdir/usr/share/spm/"
	install -Dm644 LICENSE "\$pkgdir/usr/share/licenses/\$pkgname/LICENSE"
	install -Dm644 README.md "\$pkgdir/usr/share/doc/\$pkgname/README.md"
}
PKGBUILD
