#!/usr/bin/env bash
# Generate the Nix derivation (default.nix) for a published release.
#
# Generated rather than checked in, for the same reason as the Homebrew formula:
# the derivation carries the sha256 of an archive that does not exist until the
# release is published.
#
# Usage: generate.sh <version> [sha256]
# With no sha256 the published checksum file is fetched.
set -euo pipefail

REPO="sansyourways/Sans_Password_Manager"
version="${1:-}"
[ -n "$version" ] || { printf 'usage: generate.sh <version> [sha256]\n' >&2; exit 2; }
printf '%s' "$version" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+$' || {
	printf 'generate.sh: %s is not a version\n' "$version" >&2; exit 2; }

archive="Sans_Password_Manager_v${version}.zip"
url="https://github.com/$REPO/releases/download/v${version}/${archive}"

sha="${2:-}"
if [ -z "$sha" ]; then
	sha="$(curl -fsSL "$url.sha256" | awk 'NR==1{print $1}')"
fi
printf '%s' "$sha" | grep -Eq '^[a-f0-9]{64}$' || {
	printf 'generate.sh: %s is not a sha256\n' "$sha" >&2; exit 1; }

cat <<NIX
# Generated by packaging/nix/generate.sh for $version.
# Do not edit by hand: the sha256 below belongs to one published archive.
{ lib, stdenv, fetchurl, unzip, gnupg, python3, makeWrapper }:

stdenv.mkDerivation rec {
  pname = "spm";
  version = "$version";

  src = fetchurl {
    url = "$url";
    sha256 = "$sha";
  };

  nativeBuildInputs = [ unzip makeWrapper ];
  buildInputs = [ gnupg python3 ];

  # The release archive holds spm.sh and the src/ it was built from at the top
  # level, with no wrapping directory.
  sourceRoot = ".";

  installPhase = ''
    runHook preInstall
    install -Dm755 spm.sh \$out/bin/spm
    mkdir -p \$out/share/spm
    cp -r src build.sh \$out/share/spm/
    install -Dm644 LICENSE \$out/share/doc/spm/LICENSE
    wrapProgram \$out/bin/spm \\
      --prefix PATH : \${lib.makeBinPath [ gnupg python3 ]}
    runHook postInstall
  '';

  meta = with lib; {
    description = "Single-file encrypted password manager with a CLI and a local dashboard";
    homepage = "https://github.com/$REPO";
    license = licenses.mit;
    platforms = platforms.unix;
    mainProgram = "spm";
  };
}
NIX
