#!/usr/bin/env bash
# Generate the Homebrew formula for a published release.
#
# Generated rather than checked in, because a formula carries the sha256 of an
# archive that does not exist until the release is published. A checked-in
# formula is therefore either stale or wrong, and a wrong sha256 is a formula
# that fails at `brew install` for everyone at once.
#
# Usage: generate.sh <version> [sha256]
# With no sha256 the published checksum file is fetched.
set -euo pipefail

REPO="sansyourways/Sans_Password_Manager"
version="${1:-}"
[ -n "$version" ] || { printf 'usage: generate.sh <version> [sha256]\n' >&2; exit 2; }
printf '%s' "$version" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+$' || {
	printf 'generate.sh: %s is not a version\n' "$version" >&2; exit 2; }

archive="Sans_Password_Manager_v${version}.zip"
url="https://github.com/$REPO/releases/download/v${version}/${archive}"

sha="${2:-}"
if [ -z "$sha" ]; then
	sha="$(curl -fsSL "$url.sha256" | awk 'NR==1{print $1}')"
fi
printf '%s' "$sha" | grep -Eq '^[a-f0-9]{64}$' || {
	printf 'generate.sh: %s is not a sha256\n' "$sha" >&2; exit 1; }

cat <<FORMULA
# Generated by packaging/homebrew/generate.sh for $version.
# Do not edit by hand: the sha256 below belongs to one published archive.
class Spm < Formula
  desc "Single-file encrypted password manager with a CLI and a local dashboard"
  homepage "https://github.com/$REPO"
  url "$url"
  sha256 "$sha"
  license "MIT"
  version "$version"

  depends_on "gnupg"
  depends_on "python@3.12" => :recommended

  def install
    # The release ships spm.sh together with the src/ it was built from, so an
    # installation can prove its own provenance rather than being asked to
    # trust it.
    bin.install "spm.sh" => "spm"
    pkgshare.install "src", "build.sh"
    doc.install "README.md", "CHANGELOG.md", "ROADMAP.md", "LICENSE"
  end

  test do
    assert_match "Sans Password Manager", shell_output("#{bin}/spm help")
    assert_match "$version", shell_output("#{bin}/spm --version 2>&1", 0)
  end
end
FORMULA
