#!/usr/bin/env python3
"""Fold locales/*.json into the generated region of src/spm_web_server.py.

Translators edit JSON. Nothing else. The catalogues used to live in a
JavaScript object literal inside a Python triple-quoted string inside a file
concatenated into a generated shell script, which meant a contributor adding a
language had to get Python-level escaping right inside someone else's literal.
The regression suite carried a test whose only job was to catch that escaping
going wrong, which said plainly enough that the format was the problem.

The region this writes is committed, and `./build.sh --check` verifies it is
current -- the same discipline spm.sh itself is held to.
"""

import io
import json
import os
import sys

BEGIN = "# --- BEGIN GENERATED LOCALES ---"
END = "# --- END GENERATED LOCALES ---"

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LOCALE_DIR = os.path.join(ROOT, "locales")
TARGET = os.path.join(ROOT, "src", "spm_web_server.py")

REVIEWS = ("maintained", "unreviewed")
DIRECTIONS = ("ltr", "rtl")


def load():
    """Read every catalogue, refusing anything the dashboard could not serve."""
    if not os.path.isdir(LOCALE_DIR):
        sys.exit("locales/ is missing")
    codes = sorted(
        name[:-5] for name in os.listdir(LOCALE_DIR) if name.endswith(".json"))
    if "en" not in codes:
        sys.exit("locales/en.json is the key set every other catalogue is "
                 "checked against, and it is missing")
    # English first so the fallback is the first thing a reader of the
    # generated region meets, then the rest in a stable order.
    codes = ["en"] + [code for code in codes if code != "en"]

    locales, catalogues = {}, {}
    for code in codes:
        path = os.path.join(LOCALE_DIR, "%s.json" % code)
        with io.open(path, encoding="utf-8") as handle:
            try:
                doc = json.load(handle)
            except ValueError as exc:
                sys.exit("%s.json is not valid JSON: %s" % (code, exc))
        meta = doc.get("meta")
        strings = doc.get("strings")
        if not isinstance(meta, dict) or not isinstance(strings, dict):
            sys.exit("%s.json needs a 'meta' object and a 'strings' object"
                     % code)
        if meta.get("code") != code:
            sys.exit("%s.json declares code %r, which does not match its "
                     "filename" % (code, meta.get("code")))
        for field in ("name", "english_name", "dir", "review"):
            if not meta.get(field):
                sys.exit("%s.json is missing meta.%s" % (code, field))
        if meta["dir"] not in DIRECTIONS:
            sys.exit("%s.json declares dir %r; expected one of %s"
                     % (code, meta["dir"], ", ".join(DIRECTIONS)))
        if meta["review"] not in REVIEWS:
            sys.exit("%s.json declares review %r; expected one of %s"
                     % (code, meta["review"], ", ".join(REVIEWS)))
        for key, value in strings.items():
            if not isinstance(value, str):
                sys.exit("%s.json: %s is not a string" % (code, key))
        locales[code] = {
            "name": meta["name"],
            "english_name": meta["english_name"],
            "dir": meta["dir"],
            "review": meta["review"],
        }
        catalogues[code] = strings

    english = set(catalogues["en"])
    for code in codes:
        if code == "en":
            continue
        absent = english - set(catalogues[code])
        extra = set(catalogues[code]) - english
        if absent:
            sys.exit("%s is missing %d key(s), e.g. %s"
                     % (code, len(absent), sorted(absent)[0]))
        if extra:
            sys.exit("%s has %d key(s) English does not, e.g. %s"
                     % (code, len(extra), sorted(extra)[0]))
    return codes, locales, catalogues


def render(codes, locales, catalogues):
    """Emit the region.

    Every value is a string, so json.dumps output is also valid Python, and
    ensure_ascii keeps the generated source ASCII the way the hand-written
    dictionaries were.
    """
    out = [
        BEGIN,
        "# Generated by tools/build-locales.py from locales/*.json.",
        "# Do not edit by hand -- edit the JSON and rebuild. `./build.sh --check`",
        "# verifies this region is current.",
        "WEB_LOCALES = {",
    ]
    for code in codes:
        meta = locales[code]
        out.append('    %s: {"name": %s, "english_name": %s, "dir": %s, "review": %s},' % (
            json.dumps(code),
            json.dumps(meta["name"]),
            json.dumps(meta["english_name"]),
            json.dumps(meta["dir"]),
            json.dumps(meta["review"]),
        ))
    out.append("}")
    out.append("")
    out.append("WEB_CATALOGUES = {")
    for code in codes:
        out.append("    %s: {" % json.dumps(code))
        for key in catalogues["en"]:
            out.append("        %s: %s," % (
                json.dumps(key), json.dumps(catalogues[code][key])))
        out.append("    },")
    out.append("}")
    out.append(END)
    return "\n".join(out) + "\n"


def main():
    check = "--check" in sys.argv[1:]
    codes, locales, catalogues = load()
    region = render(codes, locales, catalogues)

    with io.open(TARGET, encoding="utf-8") as handle:
        source = handle.read()
    start = source.find(BEGIN)
    stop = source.find(END)
    if start < 0 or stop < 0:
        sys.exit("the generated locale region is missing from %s"
                 % os.path.relpath(TARGET, ROOT))
    stop = source.index("\n", stop) + 1
    updated = source[:start] + region + source[stop:]

    if check:
        if updated != source:
            sys.exit("src/spm_web_server.py is stale: locales/*.json changed. "
                     "Run tools/build-locales.py.")
        print("locale region is current with locales/ (%d languages, %d keys)."
              % (len(codes), len(catalogues["en"])))
        return
    if updated != source:
        with io.open(TARGET, "w", encoding="utf-8") as handle:
            handle.write(updated)
    print("Folded %d languages (%d keys each) into src/spm_web_server.py."
          % (len(codes), len(catalogues["en"])))


if __name__ == "__main__":
    main()
